// Auto-generated by: supabase gen types typescript --local
// To regenerate: pnpm gen:types (requires supabase start)
//
// This is a placeholder. Run `supabase start && pnpm gen:types` to replace
// with real types generated from the local database schema.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      audit_logs: {
        Row: {
          id: string
          table_name: string
          record_id: string
          action: string
          old_data: Json | null
          new_data: Json | null
          performed_by: string
          performed_at: string
        }
        Insert: {
          id?: string
          table_name: string
          record_id: string
          action: string
          old_data?: Json | null
          new_data?: Json | null
          performed_by: string
          performed_at?: string
        }
        Update: {
          id?: string
          table_name?: string
          record_id?: string
          action?: string
          old_data?: Json | null
          new_data?: Json | null
          performed_by?: string
          performed_at?: string
        }
        Relationships: []
      }
      conversation_participants: {
        Row: {
          conversation_id: string
          user_id: string
          last_read_at: string | null
        }
        Insert: {
          conversation_id: string
          user_id: string
          last_read_at?: string | null
        }
        Update: {
          conversation_id?: string
          user_id?: string
          last_read_at?: string | null
        }
        Relationships: []
      }
      conversations: {
        Row: {
          id: string
          organization_id: string
          subject: string | null
          created_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          subject?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          subject?: string | null
          created_at?: string
        }
        Relationships: []
      }
      documents: {
        Row: {
          id: string
          organization_id: string
          entity_type: Database["public"]["Enums"]["document_entity_type"]
          entity_id: string
          name: string
          storage_path: string
          mime_type: string | null
          file_size_bytes: number | null
          uploaded_by: string
          created_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          entity_type: Database["public"]["Enums"]["document_entity_type"]
          entity_id: string
          name: string
          storage_path: string
          mime_type?: string | null
          file_size_bytes?: number | null
          uploaded_by: string
          created_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          entity_type?: Database["public"]["Enums"]["document_entity_type"]
          entity_id?: string
          name?: string
          storage_path?: string
          mime_type?: string | null
          file_size_bytes?: number | null
          uploaded_by?: string
          created_at?: string
        }
        Relationships: []
      }
      lease_tenants: {
        Row: {
          id: string
          lease_id: string
          user_id: string
          is_primary: boolean
          invited_at: string
          accepted_at: string | null
        }
        Insert: {
          id?: string
          lease_id: string
          user_id: string
          is_primary?: boolean
          invited_at?: string
          accepted_at?: string | null
        }
        Update: {
          id?: string
          lease_id?: string
          user_id?: string
          is_primary?: boolean
          invited_at?: string
          accepted_at?: string | null
        }
        Relationships: []
      }
      leases: {
        Row: {
          id: string
          unit_id: string
          status: Database["public"]["Enums"]["lease_status"]
          start_date: string
          end_date: string | null
          rent_amount: number
          security_deposit: number | null
          rent_due_day: number
          grace_period_days: number
          late_fee_type: string
          late_fee_amount: number | null
          signed_at: string | null
          document_url: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          unit_id: string
          status?: Database["public"]["Enums"]["lease_status"]
          start_date: string
          end_date?: string | null
          rent_amount: number
          security_deposit?: number | null
          rent_due_day?: number
          grace_period_days?: number
          late_fee_type?: string
          late_fee_amount?: number | null
          signed_at?: string | null
          document_url?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          unit_id?: string
          status?: Database["public"]["Enums"]["lease_status"]
          start_date?: string
          end_date?: string | null
          rent_amount?: number
          security_deposit?: number | null
          rent_due_day?: number
          grace_period_days?: number
          late_fee_type?: string
          late_fee_amount?: number | null
          signed_at?: string | null
          document_url?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      maintenance_attachments: {
        Row: {
          id: string
          request_id: string
          uploaded_by: string
          storage_path: string
          mime_type: string
          file_size_bytes: number | null
          created_at: string
        }
        Insert: {
          id?: string
          request_id: string
          uploaded_by: string
          storage_path: string
          mime_type: string
          file_size_bytes?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          request_id?: string
          uploaded_by?: string
          storage_path?: string
          mime_type?: string
          file_size_bytes?: number | null
          created_at?: string
        }
        Relationships: []
      }
      maintenance_comments: {
        Row: {
          id: string
          request_id: string
          author_id: string
          body: string
          is_internal: boolean
          created_at: string
        }
        Insert: {
          id?: string
          request_id: string
          author_id: string
          body: string
          is_internal?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          request_id?: string
          author_id?: string
          body?: string
          is_internal?: boolean
          created_at?: string
        }
        Relationships: []
      }
      maintenance_requests: {
        Row: {
          id: string
          unit_id: string
          submitted_by: string
          assigned_to: string | null
          title: string
          description: string
          status: Database["public"]["Enums"]["maintenance_status"]
          priority: Database["public"]["Enums"]["maintenance_priority"]
          category: string | null
          scheduled_date: string | null
          completed_at: string | null
          estimated_cost: number | null
          actual_cost: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          unit_id: string
          submitted_by: string
          assigned_to?: string | null
          title: string
          description: string
          status?: Database["public"]["Enums"]["maintenance_status"]
          priority?: Database["public"]["Enums"]["maintenance_priority"]
          category?: string | null
          scheduled_date?: string | null
          completed_at?: string | null
          estimated_cost?: number | null
          actual_cost?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          unit_id?: string
          submitted_by?: string
          assigned_to?: string | null
          title?: string
          description?: string
          status?: Database["public"]["Enums"]["maintenance_status"]
          priority?: Database["public"]["Enums"]["maintenance_priority"]
          category?: string | null
          scheduled_date?: string | null
          completed_at?: string | null
          estimated_cost?: number | null
          actual_cost?: number | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      messages: {
        Row: {
          id: string
          conversation_id: string
          sender_id: string
          body: string
          sent_at: string
        }
        Insert: {
          id?: string
          conversation_id: string
          sender_id: string
          body: string
          sent_at?: string
        }
        Update: {
          id?: string
          conversation_id?: string
          sender_id?: string
          body?: string
          sent_at?: string
        }
        Relationships: []
      }
      organization_members: {
        Row: {
          id: string
          organization_id: string
          user_id: string
          role: Database["public"]["Enums"]["org_member_role"]
          invited_at: string
          accepted_at: string | null
        }
        Insert: {
          id?: string
          organization_id: string
          user_id: string
          role: Database["public"]["Enums"]["org_member_role"]
          invited_at?: string
          accepted_at?: string | null
        }
        Update: {
          id?: string
          organization_id?: string
          user_id?: string
          role?: Database["public"]["Enums"]["org_member_role"]
          invited_at?: string
          accepted_at?: string | null
        }
        Relationships: []
      }
      organizations: {
        Row: {
          id: string
          name: string
          slug: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      payments: {
        Row: {
          id: string
          lease_id: string
          rent_charge_id: string | null
          paid_by: string
          recorded_by: string | null
          method: Database["public"]["Enums"]["payment_method_type"]
          status: Database["public"]["Enums"]["payment_status"]
          amount: number
          payment_date: string
          stripe_payment_intent_id: string | null
          stripe_charge_id: string | null
          receipt_url: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          lease_id: string
          rent_charge_id?: string | null
          paid_by: string
          recorded_by?: string | null
          method: Database["public"]["Enums"]["payment_method_type"]
          status?: Database["public"]["Enums"]["payment_status"]
          amount: number
          payment_date: string
          stripe_payment_intent_id?: string | null
          stripe_charge_id?: string | null
          receipt_url?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          lease_id?: string
          rent_charge_id?: string | null
          paid_by?: string
          recorded_by?: string | null
          method?: Database["public"]["Enums"]["payment_method_type"]
          status?: Database["public"]["Enums"]["payment_status"]
          amount?: number
          payment_date?: string
          stripe_payment_intent_id?: string | null
          stripe_charge_id?: string | null
          receipt_url?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          id: string
          full_name: string | null
          phone: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          full_name?: string | null
          phone?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string | null
          phone?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      properties: {
        Row: {
          id: string
          organization_id: string
          name: string
          address_line1: string
          address_line2: string | null
          city: string
          state: string
          zip: string
          country: string
          property_type: string | null
          year_built: number | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          name: string
          address_line1: string
          address_line2?: string | null
          city: string
          state: string
          zip: string
          country?: string
          property_type?: string | null
          year_built?: number | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          name?: string
          address_line1?: string
          address_line2?: string | null
          city?: string
          state?: string
          zip?: string
          country?: string
          property_type?: string | null
          year_built?: number | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      rent_charges: {
        Row: {
          id: string
          lease_id: string
          charge_type: Database["public"]["Enums"]["charge_type"]
          amount: number
          due_date: string
          description: string | null
          is_waived: boolean
          waived_by: string | null
          waived_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          lease_id: string
          charge_type?: Database["public"]["Enums"]["charge_type"]
          amount: number
          due_date: string
          description?: string | null
          is_waived?: boolean
          waived_by?: string | null
          waived_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          lease_id?: string
          charge_type?: Database["public"]["Enums"]["charge_type"]
          amount?: number
          due_date?: string
          description?: string | null
          is_waived?: boolean
          waived_by?: string | null
          waived_at?: string | null
          created_at?: string
        }
        Relationships: []
      }
      stripe_accounts: {
        Row: {
          id: string
          organization_id: string
          stripe_account_id: string
          charges_enabled: boolean
          payouts_enabled: boolean
          details_submitted: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          stripe_account_id: string
          charges_enabled?: boolean
          payouts_enabled?: boolean
          details_submitted?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          stripe_account_id?: string
          charges_enabled?: boolean
          payouts_enabled?: boolean
          details_submitted?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      units: {
        Row: {
          id: string
          property_id: string
          unit_number: string | null
          bedrooms: number | null
          bathrooms: number | null
          square_feet: number | null
          rent_amount: number | null
          is_available: boolean
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          property_id: string
          unit_number?: string | null
          bedrooms?: number | null
          bathrooms?: number | null
          square_feet?: number | null
          rent_amount?: number | null
          is_available?: boolean
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          property_id?: string
          unit_number?: string | null
          bedrooms?: number | null
          bathrooms?: number | null
          square_feet?: number | null
          rent_amount?: number | null
          is_available?: boolean
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      generate_late_fees: {
        Args: Record<PropertyKey, never>
        Returns: number
      }
      is_lease_tenant: {
        Args: {
          p_lease_id: string
        }
        Returns: boolean
      }
      is_org_member: {
        Args: {
          org_id: string
          roles: Database["public"]["Enums"]["org_member_role"][]
        }
        Returns: boolean
      }
      org_id_for_unit: {
        Args: {
          p_unit_id: string
        }
        Returns: string
      }
    }
    Enums: {
      charge_type: "rent" | "late_fee" | "deposit" | "utility" | "other"
      document_entity_type: "lease" | "property" | "unit" | "maintenance_request"
      lease_status: "draft" | "active" | "expired" | "terminated"
      maintenance_priority: "low" | "medium" | "high" | "emergency"
      maintenance_status: "open" | "in_progress" | "pending_approval" | "completed" | "cancelled"
      org_member_role: "owner" | "manager"
      payment_method_type: "stripe" | "cash" | "check" | "bank_transfer" | "other"
      payment_status: "pending" | "processing" | "succeeded" | "failed" | "refunded"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
